#!/bin/bash
rm -rf screens/localhost*.png
echo 'getting pages list...'
PAGES=$(curl http://localhost:4567/pages.txt)
echo 'creating screenshots...'
eval webkit2png -D screens -W 300 -H 568 --clipwidth=50 -F $PAGES
