#!/bin/bash
echo 'preparing screenshots...';
rm -rf source/screens/composed.png;
convert source/screens/*.png -background gray -bordercolor gray -border 20x20 +append source/screens/composed.png;
echo 'screenshots are ready';
