#!/bin/bash
echo 'preparing screenshots...';
rm -rf screens/composed.png;
convert screens/*.png -background gray -bordercolor gray -border 20x20 +append screens/composed.png;
echo 'screenshots are ready';
